repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        files: ^(backend/|agent/|tests/|scripts/).+\.py$

      - id: ruff
        name: ruff
        entry: ruff
        language: system
        args: ["check", "--fix"]
        types: [python]
        files: ^(backend/|agent/|tests/|scripts/).+\.py$

      - id: protect-ai-estimate
        name: Protect ai_estimate.py from unwanted changes
        entry: .git-hooks/protect_ai_estimate.sh
        language: system
        pass_filenames: false
