[tool.black]
line-length = 88
target-version = ["py38"]

[tool.ruff]
line-length = 88
target-version = "py38"
exclude = [".venv", ".local", ".cache", "node_modules", "dist", "build"]

[tool.pytest.ini_options]
addopts = "-q"
pythonpath = ["."]
