name: AI Review
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  ai-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
              with:`n          fetch-depth: 0`n- uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: python -m pip install --upgrade pip && pip install requests
      - name: Run AI review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python .github/scripts/ai_review.py
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const body = fs.existsSync('ai_review.md') ? fs.readFileSync('ai_review.md', 'utf8') : 'AI review produced no output.';
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body
            });

