name: CI
on: [pull_request]
  workflow_dispatch:
jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "no requirements.txt"
          pip install ruff mypy pytest pytest-cov
      - name: Lint
        run: ruff check .
      - name: Types
        run: mypy app || echo "mypy warnings"
      - name: Tests
        run: pytest -q --maxfail=1 --disable-warnings --cov=app

